services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /app
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - ..:/app
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file:
      - ../.env
    networks:
      - laravelnet
    depends_on:
      - mariadb
      - redis
