
services:
  soketi:
    container_name: laravel_soketi
    image: quay.io/soketi/soketi:1.4-16-debian
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      - SOKETI_METRICS_ENABLED=1
      - SOKETI_DEFAULT_APP_ID=dnmsjesus
      - SOKETI_DEFAULT_APP_KEY=dnmsjesuskey
      - SOKETI_DEFAULT_APP_SECRET=dnmsjesussecret
    restart: always
    